// LOCAL DICTIONARY 
  window.extraDigimonData = [
  { name: "Koromon", type: "Lesser", attribute: "None" },
  { name: "Tsunomon", type: "Lesser", attribute: "None" },
  { name: "Yokomon", type: "Bulb", attribute: "None" },
  { name: "Motimon", type: "Mutant", attribute: "None" },
  { name: "Tanemon", type: "Bulb", attribute: "None" },
  { name: "Bukamon", type: "Lesser", attribute: "None" },
  { name: "Tokomon", type: "Lesser", attribute: "None" },
  { name: "Agumon", type: "Reptile", attribute: "Vaccine" },
  { name: "Gabumon", type: "Reptile", attribute: "Data" },
  { name: "Biyomon", type: "Chick", attribute: "Vaccine" },
  { name: "Tentomon", type: "Insectoid", attribute: "Vaccine" },
  { name: "Palmon", type: "Plant", attribute: "Data" },
  { name: "Gomamon", type: "Sea Animal", attribute: "Vaccine" },
  { name: "Patamon", type: "Mammal", attribute: "Data" },
  { name: "Kuwagamon", type: "Insectoid", attribute: "Virus" },
  { name: "Greymon", type: "Dinosaur", attribute: "Vaccine" },
  { name: "Shellmon", type: "Mollusk", attribute: "Data" },
  { name: "Garurumon", type: "Beast", attribute: "Vaccine" },
  { name: "Seadramon", type: "Sea Animal", attribute: "Data" },
  { name: "Monochromon", type: "Ankylosaur", attribute: "Data" },
  { name: "Birdramon", type: "Giant Bird", attribute: "Vaccine" },
  { name: "Meramon", type: "Flame", attribute: "Data" },
  { name: "Kabuterimon", type: "Insectoid", attribute: "Vaccine" },
  { name: "Andromon", type: "Cyborg", attribute: "Vaccine" },
  { name: "Togemon", type: "Plant", attribute: "Data" },
  { name: "Numemon", type: "Mollusk", attribute: "Virus" },
  { name: "Monzaemon", type: "Puppet", attribute: "Vaccine" },
  { name: "Ikkakumon", type: "Sea Animal", attribute: "Vaccine" },
  { name: "Unimon", type: "Mythical Animal", attribute: "Vaccine" },
  { name: "Leomon", type: "Beast Man", attribute: "Vaccine" },
  { name: "Ogremon", type: "Evil", attribute: "Virus" },
  { name: "Devimon", type: "Fallen Angel", attribute: "Virus" },
  { name: "Frigimon", type: "Ice-Snow", attribute: "Vaccine" },
  { name: "Mojyamon", type: "Rare Animal", attribute: "Vaccine" },
  { name: "Sukamon", type: "Mutant", attribute: "Virus" },
  { name: "Centarumon", type: "Beast Man", attribute: "Data" },
  { name: "Bakemon", type: "Ghost", attribute: "Virus" },
  { name: "Elecmon", type: "Mammal", attribute: "Data" },
  { name: "Botamon", type: "Slime", attribute: "None" },
  { name: "Punimon", type: "Slime", attribute: "None" },
  { name: "Poyomon", type: "Slime", attribute: "None" },
  { name: "Yuramon", type: "Seed", attribute: "None" },
  { name: "Angemon", type: "Angel", attribute: "Vaccine" },
  { name: "Whamon", type: "Aquatic Mammal", attribute: "Vaccine" },
  { name: "Drimogemon", type: "Animal", attribute: "Data" },
  { name: "Etemon", type: "Puppet", attribute: "Virus" },
  { name: "Gazimon", type: "Mammal", attribute: "Virus" },
  { name: "Pagumon", type: "Lesser", attribute: "Virus" },
  { name: "SkullGreymon", type: "Undead", attribute: "Virus" },
  { name: "Kokatorimon", type: "Giant Bird", attribute: "Vaccine" },
  { name: "Tyrannomon", type: "Dinosaur", attribute: "Data" },
  { name: "Piximon", type: "Fairy", attribute: "Data" },
  { name: "Datamon", type: "Machine", attribute: "Virus" },
  { name: "MetalGreymon", type: "Cyborg", attribute: "Vaccine" },
  { name: "DemiDevimon", type: "Evil", attribute: "Virus" },
  { name: "WereGarurumon", type: "Beast Man", attribute: "Vaccine" },
  { name: "Digitamamon", type: "Mutant", attribute: "Data" },
  { name: "Vegiemon", type: "Carnivorous Plant", attribute: "Virus" },
  { name: "Myotismon", type: "Undead", attribute: "Virus" },
  { name: "Vademon", type: "Alien", attribute: "Virus" },
  { name: "Pabumon", type: "Slime", attribute: "None" },
  { name: "Gekomon", type: "Amphibian", attribute: "Virus" },
  { name: "Otamamon", type: "Amphibian", attribute: "Virus" },
  { name: "ShogunGekomon", type: "Amphibian", attribute: "Virus" },
  { name: "Garudamon", type: "Birdkin", attribute: "Vaccine" },
  { name: "Flymon", type: "Insectoid", attribute: "Virus" },
  { name: "Gatomon", type: "Holy Beast", attribute: "Vaccine" },
  { name: "Nanimon", type: "Invader", attribute: "Virus" },
  { name: "Devidramon", type: "Evil Dragon", attribute: "Virus" },
  { name: "Dokugumon", type: "Insectoid", attribute: "Virus" },
  { name: "Mammothmon", type: "Ancient Animal", attribute: "Vaccine" },
  { name: "Gesomon", type: "Mollusk", attribute: "Virus" },
  { name: "Raremon", type: "Undead", attribute: "Virus" },
  { name: "SkullMeramon", type: "Flame", attribute: "Data" },
  { name: "Wizardmon", type: "Demon Man", attribute: "Data" },
  { name: "Pumpkinmon", type: "Puppet", attribute: "Data" },
  { name: "Gotsumon", type: "Rock", attribute: "Data" },
  { name: "Lillymon", type: "Fairy", attribute: "Data" },
  { name: "Phantomon", type: "Ghost", attribute: "Virus" },
  { name: "DarkTyrannomon", type: "Dinosaur", attribute: "Virus" },
  { name: "Gizamon", type: "Amphibian", attribute: "Virus" },
  { name: "Zudomon", type: "Sea Animal", attribute: "Vaccine" },
  { name: "MegaSeadramon", type: "Sea Animal", attribute: "Data" },
  { name: "Angewomon", type: "Archangel", attribute: "Vaccine" },
  { name: "Tuskmon", type: "Dinosaur", attribute: "Virus" },
  { name: "Snimon", type: "Insectoid", attribute: "Vaccine" },
  { name: "MegaKabuterimon", type: "Insectoid", attribute: "Vaccine" },
  { name: "MagnaAngemon", type: "Archangel", attribute: "Vaccine" },
  { name: "VenomMyotismon", type: "Demon Lord", attribute: "Virus" },
  { name: "WarGreymon", type: "Dragonkin", attribute: "Vaccine" },
  { name: "MetalGarurumon", type: "Cyborg", attribute: "Data" },
  { name: "Nyaromon", type: "Lesser", attribute: "None" },
  { name: "Salamon", type: "Mammal", attribute: "Vaccine" },
  { name: "Parrotmon", type: "Giant Bird", attribute: "Vaccine" },
  { name: "Chuumon", type: "Beast", attribute: "Virus" },
  { name: "MetalSeadramon", type: "Cyborg", attribute: "Data" },
  { name: "Machinedramon", type: "Machine", attribute: "Virus" },
  { name: "Piedmon", type: "Demon Man", attribute: "Virus" },
  { name: "Puppetmon", type: "Puppet", attribute: "Virus" },
  { name: "Scorpiomon", type: "Crustacean", attribute: "Data" },
  { name: "Divermon", type: "Aquatic Beast Man", attribute: "Data" },
  { name: "Kiwimon", type: "Ancient Bird", attribute: "Data" },
  { name: "Mushroomon", type: "Plant", attribute: "Virus" },
  { name: "Blossomon", type: "Plant", attribute: "Data" },
  { name: "Floramon", type: "Plant", attribute: "Data" },
  { name: "Deramon", type: "Bird", attribute: "Data" },
  { name: "Cherrymon", type: "Plant", attribute: "Virus" },
  { name: "Garbagemon", type: "Mutant", attribute: "Virus" },
  { name: "MetalEtemon", type: "Cyborg", attribute: "Virus" },
  { name: "SaberLeomon", type: "Ancient Beast", attribute: "Data" },
  { name: "RedVegiemon", type: "Plant", attribute: "Virus" },
  { name: "Mekanorimon", type: "Machine", attribute: "Virus" },
  { name: "Tankmon", type: "Cyborg", attribute: "Data" },
  { name: "Hagurumon", type: "Machine", attribute: "Virus" },
  { name: "WaruMonzaemon", type: "Puppet", attribute: "Virus" },
  { name: "LadyDevimon", type: "Fallen Angel", attribute: "Virus" },
  { name: "Vilemon", type: "Evil", attribute: "Virus" },
  { name: "Apocalymon", type: "Unknown", attribute: "Unknown" },
  { name: "Kunemon", type: "Larva", attribute: "Virus" },
  { name: "Musyamon", type: "Demon Man", attribute: "Virus" },
  { name: "Starmon", type: "Mutant", attribute: "Data" },
  { name: "HerculesKabuterimon", type: "Insectoid", attribute: "Vaccine" },
  { name: "Candlemon", type: "Flame", attribute: "Data" },
  { name: "Hanumon", type: "Beast Man", attribute: "Vaccine" },
  { name: "Kokuwamon", type: "Machine", attribute: "Data" },
  { name: "Revolvermon", type: "Mutant", attribute: "Vaccine" },
  { name: "Plesiomon", type: "Plesiosaur", attribute: "Data" },
  { name: "Megadramon", type: "Cyborg", attribute: "Virus" },
  { name: "BlueMeramon", type: "Flame", attribute: "Virus" },
  { name: "Magnadramon", type: "Holy Dragon", attribute: "Vaccine" },
  { name: "Gorillamon", type: "Beast Man", attribute: "Data" },
  { name: "Syakomon", type: "Crustacean", attribute: "Virus" },
  { name: "MarineAngemon", type: "Fairy", attribute: "Vaccine" },
  { name: "Boltmon", type: "Cyborg", attribute: "Data" },
  { name: "Mamemon", type: "Mutant", attribute: "Data" },
  { name: "ExTyrannomon", type: "Puppet", attribute: "Virus" },
  { name: "Veedramon", type: "Mythical Dragon", attribute: "Vaccine" },
  { name: "AeroVeedramon", type: "Holy Dragon", attribute: "Vaccine" },
  { name: "Phoenixmon", type: "Holy Beast", attribute: "Vaccine" },
  { name: "Betamon", type: "Amphibian", attribute: "Virus" },
  { name: "Guardromon", type: "Machine", attribute: "Vaccine" },
  { name: "Penguinmon", type: "Bird", attribute: "Vaccine" },
  { name: "PlatinumSukamon", type: "Mutant", attribute: "Virus" },
  { name: "Psychemon", type: "Reptile", attribute: "Vaccine" },
  { name: "Tsukaimon", type: "Mammal", attribute: "Virus" },
  { name: "ModokiBetamon", type: "Amphibian", attribute: "Data" },
  { name: "Saberdramon", type: "Giant Bird", attribute: "Virus" },
  { name: "SnowAgumon", type: "Reptile", attribute: "Vaccine" },
  { name: "Icemon", type: "Ice-Snow", attribute: "Data" },
  { name: "Airdramon", type: "Mythical Animal", attribute: "Vaccine" },
  { name: "MetalTyrannomon", type: "Cyborg", attribute: "Virus" },
  { name: "Akatorimon", type: "Giant Bird", attribute: "Data" },
  { name: "Geremon", type: "Mollusk", attribute: "Virus" },
  { name: "Vermilimon", type: "Ankylosaur", attribute: "Data" },
  { name: "Meteormon", type: "Rock", attribute: "Data" },
  { name: "Jijimon", type: "Ancient", attribute: "Vaccine" },
  { name: "Babamon", type: "Ancient", attribute: "Vaccine" },
  { name: "FlareRizamon", type: "Flame", attribute: "Data" },
  { name: "Thunderballmon", type: "Mutant", attribute: "Data" },
  { name: "Muchomon", type: "Bird", attribute: "Data" },
  { name: "Goldramon", type: "Holy Dragon", attribute: "Vaccine" },
  { name: "Soulmon", type: "Ghost", attribute: "Virus" },
  { name: "Rosemon", type: "Fairy", attribute: "Data" },
  { name: "Piddomon", type: "Angel", attribute: "Vaccine" },
  { name: "Gigadramon", type: "Cyborg", attribute: "Virus" },
  { name: "Cyberdramon", type: "Cyborg", attribute: "Vaccine" },
  { name: "SkullSatamon", type: "Fallen Angel", attribute: "Virus" },
  { name: "Milleniummon", type: "Composition", attribute: "Virus" },
  { name: "Daemon", type: "Demon Lord", attribute: "Virus" },
  { name: "KingEtemon", type: "Puppet", attribute: "Virus" },
  { name: "Chibomon", type: "Slime", attribute: "None" },
  { name: "Pururumon", type: "Slime", attribute: "None" },
  { name: "Tsubumon", type: "Slime", attribute: "None" },
  { name: "DemiVeemon", type: "Baby Dragon", attribute: "None" },
  { name: "Poromon", type: "Mini Bird", attribute: "None" },
  { name: "Upamon", type: "Amphibian", attribute: "None" },
  { name: "Hawkmon", type: "Bird", attribute: "Free" },
  { name: "Armadillomon", type: "Mammal", attribute: "Free" },
  { name: "Wormmon", type: "Larva", attribute: "Free" },
  { name: "Flamedramon", type: "Dragonkin", attribute: "Free" },
  { name: "Raidramon", type: "Animal", attribute: "Free" },
  { name: "Magnamon", type: "Holy Knight", attribute: "Free" },
  { name: "Sethmon", type: "Demon Beast", attribute: "Free" },
  { name: "Halsemon", type: "Animal", attribute: "Free" },
  { name: "Shurimon", type: "Mutant", attribute: "Free" },
  { name: "Toucanmon", type: "Bird", attribute: "Free" },
  { name: "Submarimon", type: "Aquatic", attribute: "Free" },
  { name: "Bucchiemon", type: "Fairy", attribute: "Free" },
  { name: "Stegomon", type: "Stegosaur", attribute: "Free" },
  { name: "Pegasusmon", type: "Holy Beast", attribute: "Free" },
  { name: "Nefertimon", type: "Holy Beast", attribute: "Free" },
  { name: "ExVeemon", type: "Mythical Dragon", attribute: "Free" },
  { name: "Stingmon", type: "Mutant", attribute: "Free" },
  { name: "Aquillamon", type: "Giant Bird", attribute: "Free" },
  { name: "Ankylomon", type: "Ankylosaur", attribute: "Free" },
  { name: "Paildramon", type: "Dragonkin", attribute: "Free" },
  { name: "Dinobeemon", type: "Mutant", attribute: "Free" },
  { name: "Silphymon", type: "Beastkin", attribute: "Free" },
  { name: "Shakkoumon", type: "Mutant", attribute: "Free" },
  { name: "Imperialdramon", type: "Ancient Dragon", attribute: "Free" },
  { name: "GranKuwagamon", type: "Insectoid", attribute: "Free" },
  { name: "Valkyrimon", type: "Warrior", attribute: "Free" },
  { name: "Vikemon", type: "Beast Man", attribute: "Free" },
  { name: "Seraphimon", type: "Seraph", attribute: "Vaccine" },
  { name: "Zhuqiaomon", type: "Holy Bird", attribute: "Virus" },
  { name: "Azulongmon", type: "Holy Dragon", attribute: "Data" },
  { name: "Baihumon", type: "Holy Beast", attribute: "Data" },
  { name: "Mokumon", type: "Smoke", attribute: "None" },
  { name: "Omnimon", type: "Holy Knight", attribute: "Vaccine" }
];


window.applyFilters = function() {
    var aFilters = [];
    
    var sSearch = SearchField.getValue();
    var sLevel = comboLevel.getSelectedKey();
    var sAttr = comboAttr.getSelectedKey();
    var sType = comboType.getSelectedKey();
    var bFavsOnly = checkFavs.getSelected(); // Check if box is ticked

    if (sSearch) aFilters.push(new sap.ui.model.Filter("name", "Contains", sSearch));
    if (sLevel) aFilters.push(new sap.ui.model.Filter("level", "EQ", sLevel));
    if (sAttr) aFilters.push(new sap.ui.model.Filter("attribute", "EQ", sAttr));
    if (sType) aFilters.push(new sap.ui.model.Filter("type", "EQ", sType));

    // Favorite Filter Logic
    if (bFavsOnly) {
        var favorites = JSON.parse(localStorage.getItem("digiFavorites") || "[]");
        // Create a filter that only allows names found in our "favorites" list
        var aFavFilters = favorites.map(function(name) {
            return new sap.ui.model.Filter("name", "EQ", name);
        });
        
        if (aFavFilters.length > 0) {
            // 
            aFilters.push(new sap.ui.model.Filter({ filters: aFavFilters, and: false }));
        } else {
            // If no favorites exist, show nothing
            aFilters.push(new sap.ui.model.Filter("name", "EQ", "___EMPTY_LIST___"));
        }
    }
    
    GridList.getBinding("items").filter(aFilters);
};